# docker-compose exemplo de instalação phabricator

version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mariadb_data:/bitnami
  phabricator:
    image: bitnami/phabricator:latest
    environment:
      - PHABRICATOR_HOST=<server_ip>
      - PHABRICATOR_USERNAME=<user_name>
      - PHABRICATOR_PASSWORD=<password>
    depends_on:
      - mariadb
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - phabricator_data:/bitnami

volumes:
  mariadb_data:
  phabricator_data:
